name: Publish Preview NuGet

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**/*'
      - '**.md'
      - '**.scss'
      - '**.toml'
      - '**.html'

jobs:
  nuget:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1.5.0
        with:
          dotnet-version: '5.0.x'
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          NUGET_AUTH_TOKEN: '%NUGET_AUTH_TOKEN%'
      - name: Create and push NuGet package
        run: |
          dotnet pack -c Release -o nuget -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
          dotnet nuget push nuget/**/*.nupkg --skip-duplicate
        env:
          NUGET_AUTH_TOKEN: ${{ github.token }}
